apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "nodelocaldns.fullname" . }}
  labels:
    app: "{{ template "nodelocaldns.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "nodelocaldns.fullname" . }}
      name: {{ template "nodelocaldns.fullname" . }}
      annotations:
        checksum/configmaps: {{ tpl (toYaml .Values.configMaps) . | sha256sum }}
        checksum/secrets: {{ tpl (toYaml .Values.secrets) . | sha256sum }}
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: 1
      {{- if .Values.useHostNetwork }}
      hostNetwork: {{ .Values.useHostNetwork }}
      dnsPolicy: Default  # Don't use cluster DNS.
      {{- end }}
      {{- if .Values.useHostPID }}
      hostPID: {{ .Values.useHostPID }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
      - name: {{ default .Chart.Name .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [ "-localip", "{{ .Values.localIp }}", "-conf", "/etc/coredns/Corefile" ]
        {{- if .Values.securityContext }}
        securityContext:
 {{ toYaml .Values.securityContext | indent 12 }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.env }}
        env:
{{ include "nodelocaldns.env" . | indent 10 }}
{{- end}}
        volumeMounts:
{{ include "nodelocaldns.files.volumeMounts" . | indent 8 }}
{{ toYaml .Values.volumeMounts | indent 8 }}
{{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
{{- end }}
{{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
{{- end }}
      volumes:
{{ include "nodelocaldns.files.volumes" . | indent 6 }}
{{ toYaml .Values.volumes | indent 6 }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "nodelocaldns.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
  updateStrategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
